background #282c34
foreground #bbc2cf

selection_background #2257A0
selection_foreground #bbc2cf

cursor #51afef

color0 #282c34
color8 #3f444a

color1 #ff6c6b
color9 #ff6c6b

color2 #98be65
color10 #98be65

color3 #ECBE7B
color11 #ECBE7B

color4 #51afef
color12 #66d9ef

color5 #a9a1e1
color13 #a9a1e1

color6 #49D9FF
color14 #46D9FF

color7 #bbc2cf
color15 #f8f8f2
