background #1c1d27
foreground #E9DBDB

cursor #23D18C
selection_background #424b54
selection_foreground #E9DBDB

# ==== COLORS ====================
# ================================
# Black
color0 #1b1d1e
color8 #424b54

# Red
color1 #E84855
color9 #FF5D8F

# Yellow
color2 #EAB466
color10 #ffe066

# Green
color3 #23D18C
color11 #24f09f

# Blue
color4 #0060ce
color12 #007fce

# Magenta
color5 #A29BFE
color13 #b3adff

# Cyan
color6 #00CECB
color14 #00f0ec

# White
color7 #E9DBDB
color15 #f8f8f2

# vim: ft=conf
